version: "2"

services:
  mpi_head:
    image: cwpearson/openmpi
    ports: 
      - "22"
    links: 
      - mpi_node
    networks:
      - net

  mpi_node:
    image: cwpearson/openmpi
    networks:
      - net

networks:
  net:
    driver: bridge